name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      apply: true
      aws-assume-role-arn: "arn:aws:iam::599528519972:role/githubactions-tripradar-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "lucaslima-dev-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "lucaslima-dev-sa-east-1-terraform-lock"